version: '3.7'

services:
  updater:
    image: "menoncello/podcast-manager.itunes-crawler"
    environment:
      MongoUrl: ${MONGO_URL}
      RabbitUrl: ${RABBIT_URL}
    networks:
      - backend
    deploy:
      mode: global

networks:
  backend:
    external: true